# Generated by Django 5.2.11 on 2026-02-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0002_bookmark_deleted_at_bookmark_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="genre",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("study", "Study"),
                    ("learning", "Learning"),
                    ("personal", "Personal"),
                ],
                default="work",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
