# Generated by Django 5.2.11 on 2026-02-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0003_remove_bookmark_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="genre",
            field=models.CharField(max_length=50),
        ),
    ]
